version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: jobs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - './postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
